name: 'Docker Python action'
description: 'this action executes a python script using a docker container'
inputs:
  python-user:  
    description: 'the user password'
    required: true
  python-password:  
    description: 'the user name'
    required: true
  bastion-host:  
    description: 'the bastion host IP adress'
    required: true
  remote-host:  
    description: 'the remote host IP adress'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
