name: 'Docker Python action'
description: 'this action executes a python script using a docker container'
inputs:
  python-action:  
    description: 'the name of the python function to be execute'
    required: true
    default: 'echo'
  python-user:  
    description: 'the user name'
    required: false
    default: 'guest'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.python-action }}