name: 'Docker Python action'
description: 'this action executes a python script using a docker container'
inputs:
  python-action:  
    description: 'the name of the python function to be execute'
    required: true
    default: 'echo'
  python-user:  
    description: 'the user name'
    required: true
    default: 'guest'
